### ISSUE TITLE
Enable Configurable consumer_config in DataHub Action Docker Image

### ISSUE THREAD

**Issue by wornjs** [acryldata/datahub-actions#166]
**Issue Description**
Currently, the executor.yaml configuration in the DataHub Action Docker image only supports plain-text Kafka connections. This limitation prevents connections to Kafka clusters that require SSL/SASL authentication or other advanced configurations.

To enhance compatibility, we should allow users to specify consumer_config dynamically using environment variables. This change will enable DataHub Actions to connect to more secure Kafka environments seamlessly.

**Proposed Solution**
Modify the Docker image to read environment variables at runtime and generate the executor.yaml file accordingly. The updated configuration should support additional consumer_config parameters based on environment variables.

**Example executor.yaml after modification**
```yaml
source:
  type: "kafka"
  config:
    connection:
      bootstrap: ${KAFKA_BOOTSTRAP_SERVER:-localhost:9092}
      schema_registry_url: ${SCHEMA_REGISTRY_URL:-http://localhost:8081}
    topic_routes:
      mcl: ${METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME:-MetadataChangeLog_Versioned_v1}
      pe: ${PLATFORM_EVENT_TOPIC_NAME:-PlatformEvent_v1}
    consumer_config:
      # Add dynamic consumer config based on environment variables
```

This approach ensures that users can configure Kafka connections dynamically without modifying the Docker image or manually editing executor.yaml.

Let’s implement this enhancement to improve flexibility and security in DataHub Actions
