### ISSUE TITLE
Permission error while accessing /tmp/datahub

### ISSUE THREAD

**Issue by upendrao** [acryldata/datahub-actions#79]
**Problem description**:
datahub-actions component fails to process incoming ingestion requests as it fails to create ingestion recipe yaml file at `/tmp/datahub/ingest` folder

**Environment**:
- datahub helm chart v0.2.144
- Datahub 0.9.6.1
- datahub-actions v0.0.8
- Kubernetes v1.26.0

**How to reproduce?**
Run datahub-actions in k8s v1.26.0 with following securityContext configuration.
```
acryl-datahub-actions:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: "RuntimeDefault"
```
**Observations**:
- Pod security context enforces the pods in k8s v1.26.0 requires all pods to be `runAsNonRoot: true` which implies one had to specify a user-id in `securityContext`
- The `/tmp/datahub` folder is created and owned by a system user 'datahub' as per Dockerfile [here](https://github.com/acryldata/datahub-actions/blob/792a8a8a7e33959ec3ebe95a3dde030438298f8a/docker/datahub-actions/Dockerfile#L35)
- `datahub-actions` startup script is started by the user with id 1000 which overrides the intended `USER datahub` specified in Dockerfile
- So all datahub-actions scripts cannot access `/tmp/datahub` folder 

Questions?
- What was the need for a special `datahub` system user?
- Why do you need to protect `/tmp/datahub` for `datahub` user
